routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
use App\User;


Route::get('/', function () {
    //return view('welcome');
	//$rol = RoleSchool::all();
    return view('admin');
})->name('/');

Route::any('template',function(){
	return view('admin.index');
})->name('template');

Route::any('show',function(Request $request){

	$id = $request->get('id');

	$aviso = \App\Avisos::findOrFail($id);

	return $aviso;
})->name('avisos.show');

/*------------- Nuevo Registro -----------*/
Route::any('registro','Auth\RegisterController@showRegistrationForm')->name('nuevo');

Route::any('newuser', function(Request $request){

	$client = new User();
	$client->name = $request->get('name');
    $client->email = $request->get('email');
    $client->password = Hash::make($request->get('password'));       
	$client->roles_id = $request->get('roles');
	$addUser = $client->save();

	if ($addUser) {
        return redirect()->route('login')->with('mensajeDeusuario','Ya creaste un usuario ahora logueate');
    }
        return redirect()->route('login')->with('mensajeDeusuarioError','Pofavor Contacta al Administrador');
})->name('register');

/* ------------ Documentos ---------------*/

Route::any('index','DocumentsController@index')->name('documentos.index');
Route::any('add','DocumentsController@create')->name('documentos.create');
Route::any('save','DocumentsController@store')->name('documentos.store');
Route::any('show/{id}','DocumentsController@edit')->name('documentos.edit');
Route::any('download/{id}','DocumentsController@download')->name('documentos.download');

/* ------------ Documentos ---------------*/

//Route::resource('data','FirstController')->name('data');
Route::resource('alumno','FirstController');

/*  ---------- Avisos ------------ */
Route::any('avisos',['uses'=>'AvisosController@index'])->name('avisos');
Route::any('create',['uses'=>'AvisosController@create'])->name('avisos.create');
Route::any('store',['uses'=>'AvisosController@store'])->name('avisos.store');
Route::any('edit/{id}',['uses'=>'AvisosController@edit'])->name('avisos.edit');
Route::any('update/{id}',['uses'=>'AvisosController@update'])->name('avisos.update');
Route::any('destroy/{id}',['uses'=>'AvisosController@destroy'])->name('avisos.destroy');
//Route::any('show',['uses'=>'AvisosController@show'])->name('avisos.show');
/*  ---------- Avisos ------------ */

Route::resource('materias','MateriasController');
Route::resource('gradoescolar','GradoEscolarController');
Route::resource('grupos','GruposController');
Route::resource('horarioAlumnos','HorarioAlumnosController');
Route::resource('horarioDocentes','HorarioDocentesController');
Route::resource('Docentes','DocentesController');
Route::resource('calificaciones','CalificacionesController');
Route::resource('orientador','OrientadoresController');
Route::resource('users','UsersController');

/*  ---------- Eventos ------------ */

Route::any('eventos','EventosController@index')->name('eventos.index');

Route::any('create','EventosController@create')->name('eventos.create');
Route::any('store','EventosController@store')->name('eventos.store');

Route::any('editEventos/{id}','EventosController@edit')->name('editEventos');

Route::any('updateEventos/{id}','EventosController@update')->name('updateEventos');

Route::any('down/{id}','EventosController@download')->name('download');

Route::any('destroy/{id}','EventosController@destroy')->name('delete');

/*  ---------- Eventos ------------ */


/* -------- LOGIN ---------- */
Route::any('login','Auth\LoginController@showLoginForm')->name('login');

Route::any('ac','Auth\LoginController@login');

Route::any('logout','Auth\LoginController@logout')->name('logout');
/* -------- LOGIN ---------- */



/* -------- Mail ---------- */
Route::any('mail','MailController@index')->name('mail');


/* ---------- Calendar --------- */

Route::any('calendarAdd','CalendarEventAddController@add')->name('calendarAdd');

Route::any('calendarEdit','CalendarEventAddController@edit')->name('calendarEdit');

Route::any('calendarDelete','CalendarEventAddController@destroy')->name('calendarDelete');


//Route::any('validate','LogController@validacion');



Route::any('recib','MailController@imap');

Route::group(['prefix' => 'modulos'], function() {
	/* -------- Modulo ---------- */
	Route::any('modulo',['uses'=>'ModuloController@index'])->name('modulo');
	Route::any('data',['uses'=>'ModuloController@store'])->name('data');
	/* -------- Modulo ---------- */

	Route::any('ajax','LogController@allData')->name('send');

	Route::any('pos','LogController@slave')->name('pos');

	Route::any('kenshidog','LogController@index')->name('XD');


	Route::any('ajaxR','LogController@showAlu')->name('laravel');

	Route::any('deleteA','LogController@deleteRow')->name('deleteA');

	
	/*  --------- Materias Docentes -------- */
	Route::any('materiaMaestro','LogController@maestrosMaterias')->name('mM');
	Route::any('mMaestro','LogController@query')->name('mMa');
	Route::any('posM','LogController@pinaple')->name('posM');
	Route::any('pivot','LogController@getPivot')->name('pivot');
	/*  --------- Materias Docentes -------- */
});

Route::group(['prefix' => 'reportes'], function(){

	Route::any('gruposalumnosR',['uses'=>'LogController@GAR'])->name('GAR');
	Route::any('report',['uses'=>'LogController@show'])->name('report');

	Route::any('maestrosMaterias',['uses'=>'LogController@reporteMM'])->name('MM');
	Route::any('reportMM',['uses'=>'LogController@showMM'])->name('reportMM');
	
});

Route::group(['prefix' => 'Calificaciones'], function(){

	Route::any(
		'asignacionCalificaciones', 
		['uses'=>'LogController@cal']
	)->name('cal');

	Route::any('query','LogController@querytodocentes')->name('querytodocentes');

	Route::any('getAlumno','LogController@showA')->name('datafromAlumno');

	Route::any('save','LogController@save')->name('saveGrade');
	
});




Route::any('reporte', 'LogController@reporteExcel')->name('reporte');


use Maatwebsite\Excel\Facades\Excel;

Route::any('exportToexcel/{id}', function($id){

	
	$reporte = \DB::select("SELECT
	gru.nombreG AS grupo,
	mat.nombreDelamateria AS materia,
	alumno.nombre,
	calificacion.C1 AS PrimerParcial,
	calificacion.C2 AS SegundoParcial,
	calificacion.C3 AS TercerParcial,
	calificacion.C4 AS CuartoParcial,
	calificacion.C5 AS QuintoParcial,
	setCalificaciones(alumno.nombre) AS promedioGral
	FROM calificaciones AS calificacion

	INNER JOIN alumnos AS alumno
	ON alumno.idA = calificacion.idA

	INNER JOIN materia AS mat
	ON mat.idMateria = calificacion.idMateria

	INNER JOIN detalle_grupos_calificaciones AS detalle
	ON detalle.idCalificacion = calificacion.idCalificacion

	INNER JOIN grupo AS gru
	ON gru.idGrupo = detalle.idGrupo

	INNER JOIN docentes AS docente
	ON docente.idD = calificacion.idD

	WHERE gru.idGrupo = $id ");
	//dd($reporte);
    $file = date('d-m-Y');

	Excel::create("$file", function($excel) use($reporte) {

	    $excel->sheet('Sheetname', function($sheet) use($reporte) {

	        $sheet->loadView('reportes.excel',compact('reporte'));

	    });

	})->export('xlsx');
	
	
})->name('exportToexcel');

/*  ---------- Dates Controller -------- */
Route::resource('citas','DateController');
/*  ---------- Dates Controller -------- */



/*  ---------- PayPal -------- */
Route::any('paypal','PaypalController@index')->name('beki');

Route::any('pay','PaypalController@payWithpaypal')->name('payd');

Route::any('status','PaypalController@getPaymentStatus')->name('status');
/*  ---------- PayPal -------- */


/*  ---------- Combo de retroalimentacion PayPal -------- */
Route::any('paymethod','PaypalController@comboPay')->name('combo');
Route::any('consulta', 'PaypalController@cantidadP')->name('consultaP');
/*  ---------- Combo de retroalimentacion PayPal -------- */

/* ------------ Banner Publicitario ------------- */
Route::any('banner','BannersController@index')->name('banner.index');
Route::any('create','BannersController@create')->name('banner.create');
Route::any('store','BannersController@store')->name('banner.store');
Route::any('edit/{id}','BannersController@edit')->name('banner.edit');
Route::any('update/{id}','BannersController@update')->name('banner.update');
Route::any('destroy/{id}','BannersController@destroy')->name('banner.destroy');
/* ------------ Banner Publicitario ------------- */

/*------------- Sales Registro -----------*/
Route::any('Sales','SalesController@index')->name('ventas');

Route::any('seach','SalesController@buscar')->name('busqueda');

resources/views/horariosAlumnos/create.blade.php
@extends('layout.layout')

@section('centro')
	<div class="col-md-12">
        <div class="card card-statistics">
        	<div class="card-header">
        		<h3><p>
        			Horari de Alumnos &nbsp;
        			
        		</p></h3>
        	</div>
            <div class="card-body">
                  	{!!  Form::open(['route'=>'horarioAlumnos.store', 'method' => 'POST']) !!}
						<div class="form-group">
							{!! Form::label('dia', 'Dia') !!}

							{!! Form::text('dia',null,['class'=>'form-control','placeholder'=>'Dia']) !!}
							<span style="color: red;">{!! $errors->first('dia') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('docente', 'Alumno') !!}
							<select class="form-control" name="idA">
							@foreach ($alumnos as $i)
								<option value="{{ $i->idA }}">{{ $i->nombre }}</option>
							@endforeach
							</select>
							<span style="color: red;">{!! $errors->first('idA') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('grupo', 'Materia') !!}
							<select class="form-control" name="idMateria">
							@foreach ($materia as $m)
								<option value="{{ $m->idMateria }}">
									{{ $m->claveDemateria }}
									&nbsp;
									{{ $m->nombreDelamateria }}
								</option>
							@endforeach
							</select>
							<span style="color: red;">{!! $errors->first('idMateria') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('dia', 'Hora de Inicio') !!}

							
							{{ Form::time('horaInicio', null, ['class'=>'form-control','placeholder'=>'hora'] ) }}
							<span style="color: red;">{!! $errors->first('horaInicio') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('dia', 'Hora de Termino') !!}

							{{ Form::time('horaFin', null, ['class'=>'form-control','placeholder'=>'hora'] ) }}
							<span style="color: red;">{!! $errors->first('horaFin') !!}</span>
						</div>
						{!! Form::submit('Save!',['class'=>'btn btn-success']) !!}
					{!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

@section('script')

@stop

resources/views/horariosAlumnos/edit.blade.php
@extends('layout.layout')

@section('centro')
	<div class="col-md-12">
        <div class="card card-statistics">
        	<div class="card-header">
        		<h3><p>
        			Horario de Alumnos &nbsp;
        			
        		</p></h3>
        	</div>
            <div class="card-body">
                  	{!!  Form::open(['route'=>array('horarioAlumnos.update',$edit->idHorarioA), 'method' => 'POST']) !!}
                  	@method('PUT')
						<div class="form-group">
							{!! Form::label('dia', 'Dia') !!}

							{!! Form::text('dia',$edit->dia,['class'=>'form-control','placeholder'=>'Dia']) !!}
							<span style="color: red;">{!! $errors->first('dia') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('docente', 'Alumno') !!}
							<select class="form-control" name="idA">
								<option value="{{ $edit->alumnos->idA }}">
									{{ $edit->alumnos->nombre }}
								</option>
								@foreach ($alumnos as $i)
									<option value="{{ $i->idA }}">
										{{ $i->nombre }}
									</option>
								@endforeach
							</select>
							<span style="color: red;">{!! $errors->first('idA') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('grupo', 'Grupo') !!}
							
							<select class="form-control" name="idMateria">
								<option value="{{ $edit->materias->idMateria }}">

									{{ $edit->materias->nombreDelamateria }}
									
								</option>
								@foreach($materias as $x)
									<option value="{{ $x->idMateria }}">
										{{ $x->nombreDelamateria }}
									</option>
								@endforeach
							</select>
							<span style="color: red;">{!! $errors->first('idMateria') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('dia', 'Hora de Inicio') !!}

							
							{{ Form::time('horaInicio',$edit->horaInicio, ['class'=>'form-control','placeholder'=>'hora'] ) }}
							<span style="color: red;">{!! $errors->first('horaInicio') !!}</span>
						</div>
						<div class="form-group">
							{!! Form::label('dia', 'Hora de Termino') !!}

							{{ Form::time('horaFin',$edit->horaFin, ['class'=>'form-control','placeholder'=>'hora'] ) }}
							<span style="color: red;">{!! $errors->first('horaFin') !!}</span>
						</div>
						{!! Form::submit('Save!',['class'=>'btn btn-success']) !!}
					{!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

@section('script')

@stop

resources/views/horariosAlumnos/index.blade.php
@extends('layout.layout')

@section('centro')
	<div class="col-md-12">
            @if( session()->has('ok') )
        <div class="alert alert-success" role="alert">
          {{ session()->get('ok') }}
        </div>
        @elseif(session()->has('error'))
        <div class="alert alert-danger" role="alert">
            {{ session()->get('error') }}
        </div>
        @endif
        <div class="card card-statistics">
        	<div class="card-header">
        		<h3><p>
        			Horarios Alumnos &nbsp;
        			<a href="{{ route('horarioAlumnos.create') }}"> 
        				<button class="btn btn-success">
        					New
        				</button>
        			</a>
        		</p></h3>
        	</div>
            <div class="card-body">
                  <table class="table table-hover">
                  	<thead>
                  		<tr>
                  			<th>Nombre del Alumno</th>
                  			<th>Dia de clase</th>
                  			<th>Clave de la materia</th>
                        <th>Nombre de la Materia</th>
                        <th>Hora de inicio</th>
                        <th>Hora de Fin</th>
                  			<th>Options</th>
                  		</tr>
                  	</thead>
                  	<tbody>
                      @forelse ($query as $i)
                        <tr>
                          <td>
                            {!! $i->nombre !!}
                          </td>
                          <td>
                            {{ $i->dia }}
                          </td>
                          <td>
                            {{ $i->claveDemateria }}
                          </td>
                          <td>
                            {!! $i->nombreDelamateria !!}
                          </td>
                          <td>
                            {!! $i->horaInicio !!}
                          </td>
                          <td>
                            {{ $i->horaFin }}
                          </td>
                          <td>
                            <a href="{{ route('horarioAlumnos.edit',$i->idHorarioA ) }}">
                              <button class="btn btn-info">Edit</button>
                            </a>
                            &nbsp;
                            <form action="{{ route('horarioAlumnos.destroy',$i->idHorarioA ) }}" method="POST">
                              @csrf

                              {{ method_field('DELETE') }}
                              <button class="btn btn-danger">Delete</button>
                            </form>
                          </td>
                        </tr>
                      @empty
                        <p>Sin Registros...</p> 
                      @endforelse
                  	</tbody>
                  </table>
            </div>
        </div>
    </div>
@stop
@section('js')
@stop