routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
use App\User;


Route::get('/', function () {
    //return view('welcome');
	//$rol = RoleSchool::all();
    return view('admin');
})->name('/');

Route::any('template',function(){
	return view('admin.index');
})->name('template');

Route::any('show',function(Request $request){

	$id = $request->get('id');

	$aviso = \App\Avisos::findOrFail($id);

	return $aviso;
})->name('avisos.show');

/*------------- Nuevo Registro -----------*/
Route::any('registro','Auth\RegisterController@showRegistrationForm')->name('nuevo');

Route::any('newuser', function(Request $request){

	$client = new User();
	$client->name = $request->get('name');
    $client->email = $request->get('email');
    $client->password = Hash::make($request->get('password'));       
	$client->roles_id = $request->get('roles');
	$addUser = $client->save();

	if ($addUser) {
        return redirect()->route('login')->with('mensajeDeusuario','Ya creaste un usuario ahora logueate');
    }
        return redirect()->route('login')->with('mensajeDeusuarioError','Pofavor Contacta al Administrador');
})->name('register');

/* ------------ Documentos ---------------*/

Route::any('index','DocumentsController@index')->name('documentos.index');
Route::any('add','DocumentsController@create')->name('documentos.create');
Route::any('save','DocumentsController@store')->name('documentos.store');
Route::any('show/{id}','DocumentsController@edit')->name('documentos.edit');
Route::any('download/{id}','DocumentsController@download')->name('documentos.download');

/* ------------ Documentos ---------------*/

//Route::resource('data','FirstController')->name('data');
Route::resource('alumno','FirstController');

/*  ---------- Avisos ------------ */
Route::any('avisos',['uses'=>'AvisosController@index'])->name('avisos');
Route::any('create',['uses'=>'AvisosController@create'])->name('avisos.create');
Route::any('store',['uses'=>'AvisosController@store'])->name('avisos.store');
Route::any('edit/{id}',['uses'=>'AvisosController@edit'])->name('avisos.edit');
Route::any('update/{id}',['uses'=>'AvisosController@update'])->name('avisos.update');
Route::any('destroy/{id}',['uses'=>'AvisosController@destroy'])->name('avisos.destroy');
//Route::any('show',['uses'=>'AvisosController@show'])->name('avisos.show');
/*  ---------- Avisos ------------ */

Route::resource('materias','MateriasController');
Route::resource('gradoescolar','GradoEscolarController');
Route::resource('grupos','GruposController');
Route::resource('horarioAlumnos','HorarioAlumnosController');
Route::resource('horarioDocentes','HorarioDocentesController');
Route::resource('Docentes','DocentesController');
Route::resource('calificaciones','CalificacionesController');
Route::resource('orientador','OrientadoresController');
Route::resource('users','UsersController');

/*  ---------- Eventos ------------ */

Route::any('eventos','EventosController@index')->name('eventos.index');

Route::any('create','EventosController@create')->name('eventos.create');
Route::any('store','EventosController@store')->name('eventos.store');

Route::any('editEventos/{id}','EventosController@edit')->name('editEventos');

Route::any('updateEventos/{id}','EventosController@update')->name('updateEventos');

Route::any('down/{id}','EventosController@download')->name('download');

Route::any('destroy/{id}','EventosController@destroy')->name('delete');

/*  ---------- Eventos ------------ */


/* -------- LOGIN ---------- */
Route::any('login','Auth\LoginController@showLoginForm')->name('login');

Route::any('ac','Auth\LoginController@login');

Route::any('logout','Auth\LoginController@logout')->name('logout');
/* -------- LOGIN ---------- */



/* -------- Mail ---------- */
Route::any('mail','MailController@index')->name('mail');


/* ---------- Calendar --------- */

Route::any('calendarAdd','CalendarEventAddController@add')->name('calendarAdd');

Route::any('calendarEdit','CalendarEventAddController@edit')->name('calendarEdit');

Route::any('calendarDelete','CalendarEventAddController@destroy')->name('calendarDelete');


//Route::any('validate','LogController@validacion');



Route::any('recib','MailController@imap');

Route::group(['prefix' => 'modulos'], function() {
	/* -------- Modulo ---------- */
	Route::any('modulo',['uses'=>'ModuloController@index'])->name('modulo');
	Route::any('data',['uses'=>'ModuloController@store'])->name('data');
	/* -------- Modulo ---------- */

	Route::any('ajax','LogController@allData')->name('send');

	Route::any('pos','LogController@slave')->name('pos');

	Route::any('kenshidog','LogController@index')->name('XD');


	Route::any('ajaxR','LogController@showAlu')->name('laravel');

	Route::any('deleteA','LogController@deleteRow')->name('deleteA');

	
	/*  --------- Materias Docentes -------- */
	Route::any('materiaMaestro','LogController@maestrosMaterias')->name('mM');
	Route::any('mMaestro','LogController@query')->name('mMa');
	Route::any('posM','LogController@pinaple')->name('posM');
	Route::any('pivot','LogController@getPivot')->name('pivot');
	/*  --------- Materias Docentes -------- */
});

Route::group(['prefix' => 'reportes'], function(){

	Route::any('gruposalumnosR',['uses'=>'LogController@GAR'])->name('GAR');
	Route::any('report',['uses'=>'LogController@show'])->name('report');

	Route::any('maestrosMaterias',['uses'=>'LogController@reporteMM'])->name('MM');
	Route::any('reportMM',['uses'=>'LogController@showMM'])->name('reportMM');
	
});

Route::group(['prefix' => 'Calificaciones'], function(){

	Route::any(
		'asignacionCalificaciones', 
		['uses'=>'LogController@cal']
	)->name('cal');

	Route::any('query','LogController@querytodocentes')->name('querytodocentes');

	Route::any('getAlumno','LogController@showA')->name('datafromAlumno');

	Route::any('save','LogController@save')->name('saveGrade');
	
});




Route::any('reporte', 'LogController@reporteExcel')->name('reporte');


use Maatwebsite\Excel\Facades\Excel;

Route::any('exportToexcel/{id}', function($id){

	
	$reporte = \DB::select("SELECT
	gru.nombreG AS grupo,
	mat.nombreDelamateria AS materia,
	alumno.nombre,
	calificacion.C1 AS PrimerParcial,
	calificacion.C2 AS SegundoParcial,
	calificacion.C3 AS TercerParcial,
	calificacion.C4 AS CuartoParcial,
	calificacion.C5 AS QuintoParcial,
	setCalificaciones(alumno.nombre) AS promedioGral
	FROM calificaciones AS calificacion

	INNER JOIN alumnos AS alumno
	ON alumno.idA = calificacion.idA

	INNER JOIN materia AS mat
	ON mat.idMateria = calificacion.idMateria

	INNER JOIN detalle_grupos_calificaciones AS detalle
	ON detalle.idCalificacion = calificacion.idCalificacion

	INNER JOIN grupo AS gru
	ON gru.idGrupo = detalle.idGrupo

	INNER JOIN docentes AS docente
	ON docente.idD = calificacion.idD

	WHERE gru.idGrupo = $id ");
	//dd($reporte);
    $file = date('d-m-Y');

	Excel::create("$file", function($excel) use($reporte) {

	    $excel->sheet('Sheetname', function($sheet) use($reporte) {

	        $sheet->loadView('reportes.excel',compact('reporte'));

	    });

	})->export('xlsx');
	
	
})->name('exportToexcel');

/*  ---------- Dates Controller -------- */
Route::resource('citas','DateController');
/*  ---------- Dates Controller -------- */



/*  ---------- PayPal -------- */
Route::any('paypal','PaypalController@index')->name('beki');

Route::any('pay','PaypalController@payWithpaypal')->name('payd');

Route::any('status','PaypalController@getPaymentStatus')->name('status');
/*  ---------- PayPal -------- */


/*  ---------- Combo de retroalimentacion PayPal -------- */
Route::any('paymethod','PaypalController@comboPay')->name('combo');
Route::any('consulta', 'PaypalController@cantidadP')->name('consultaP');
/*  ---------- Combo de retroalimentacion PayPal -------- */

/* ------------ Banner Publicitario ------------- */
Route::any('banner','BannersController@index')->name('banner.index');
Route::any('create','BannersController@create')->name('banner.create');
Route::any('store','BannersController@store')->name('banner.store');
Route::any('edit/{id}','BannersController@edit')->name('banner.edit');
Route::any('update/{id}','BannersController@update')->name('banner.update');
Route::any('destroy/{id}','BannersController@destroy')->name('banner.destroy');
/* ------------ Banner Publicitario ------------- */

/*------------- Sales Registro -----------*/
Route::any('Sales','SalesController@index')->name('ventas');

Route::any('seach','SalesController@buscar')->name('busqueda');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use App\Log;

class UsersController extends Controller
{
    function __construct(){
        $this->middleware(['auth','roles']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::all();

        return view('user.index',compact('users') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $roles = Log::all();

        return view('user.create',compact('roles') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        dd( $request->all() );
        //User::create( $request->all() );
        /*
        $addUser = User::create([
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'roles_id' => $request->get('roles_id')
        ]);

        if ($addUser) {
            return redirect()->route('login')->with('mensajeDeusuario','Ya creaste un usuario ahora logueate');
        }
            return redirect()->route('login')->with('mensajeDeusuarioError','Pofavor Contacta al Administrador');
        */    
        //return redirect()->route('users.index')->with('ok','Creado Exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/create.blade.php
@extends('layout.layout')

@section('centro')
	
	<div class="col-md-12">
            @if( session()->has('ok') )
        <div class="alert alert-success" role="alert">
          {{ session()->get('ok') }}
        </div>
        @elseif(session()->has('error'))
        <div class="alert alert-danger" role="alert">
            {{ session()->get('error') }}
        </div>
        @endif
        <div class="card card-success">
        	<div class="card-header">
        		<h3><p>
        			Users &nbsp;
        		</p></h3>
        	</div>
            <div class="card-body">
                 <form action="{{ route('users.store') }}" method="POST">

                   <div class="form-group">
                     <label>Name</label>
                     <input type="text" name="name" class="form-control">
                   </div>
                   <div class="form-group">
                     <label>Email</label>
                     <input type="email" name="email" class="form-control">
                   </div>
                   <div class="form-group">
                     <label>Password</label>
                     <input type="password" name="password" class="form-control">
                   </div>
                   <div class="form-group">
                     <label>Roles</label>
                     <select class="form-control" name="roles_id">
                       @foreach ($roles as $r)
                        <option value="{{ $r->id }}">
                          {{ $r->role }}
                        </option>
                       @endforeach
                     </select>
                   </div>
                   <button type="submit" class="btn btn-success">Save</button>
                 </form>
            </div>
        </div>
    </div>

@stop

resources/views/user/index.blade.php
@extends('layout.layout')

@section('centro')
	
	<div class="col-md-12">
            @if( session()->has('ok') )
        <div class="alert alert-success" role="alert">
          {{ session()->get('ok') }}
        </div>
        @elseif(session()->has('error'))
        <div class="alert alert-danger" role="alert">
            {{ session()->get('error') }}
        </div>
        @endif
        <div class="card card-success">
        	<div class="card-header">
        		<h3><p>
        			Users &nbsp;
        			<a href="{{ route('users.create') }}"> 
        				<button class="btn btn-success">
        					New
        				</button>
        			</a>
        		</p></h3>
        	</div>
            <div class="card-body">
                 <table class="table table-hover">
                   <thead>
                     <tr style="background-color: #FF5733;">
                      <th>Name</th>
                      <th>Email</th>
                      <th>OPT</th>
                     </tr>
                   </thead>
                   <tbody>
                    @foreach ($users as $i)
                      <tr>
                        <td>
                          
                        	{{ $i->name }}
                        </td>
                        <td>
                          {{ $i->email }}
                        </td>

                        <td>
                          <a href="{{ route('users.edit',$i->id) }}">
                            <button class="btn btn-info edit">
                              Edit
                            </button>
                          </a>
                          &nbsp;
                          <form action="{{ route('users.destroy',$i->id) }}" method="POST">
                            @csrf
                            {{ method_field('DELETE') }}
                            <button class="btn btn-danger">
                              Delete
                            </button>
                          </form>
                        </td>
                      </tr>
                    @endforeach
                   </tbody>
                 </table> 
            </div>
        </div>
    </div>

@stop